apiVersion: v1
kind: Service
metadata:
  name: peterengland-website-service
  labels:
    app: peterengland-website
spec:
  type: LoadBalancer
  selector:
    app: peterengland-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
