apiVersion: apps/v1
kind: Deployment
metadata:
  name: level-devil-game
  labels:
    app: level-devil-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: level-devil-game
  template:
    metadata:
      labels:
        app: level-devil-game
    spec:
      containers:
      - name: level-devil-game
        image: varaprasadrenati/level-devil-game:d922c6d1
        ports:
        - containerPort: 3000
