apiVersion: v1
kind: Service
metadata:
  name: level-devil-game-service
  labels:
    app: level-devil-game
spec:
  type: LoadBalancer
  selector:
    app: level-devil-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
